project_id = "xwdrvakfrhlrnvqxodft"

[functions.datafast-checkout]
verify_jwt = false

[functions.datafast-status]
verify_jwt = false

[functions.process-paypal-purchase]
verify_jwt = false

[functions.hotmart-webhook]
verify_jwt = false